server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
    #    service-url:
    #      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001 #修改服务名
    prefer-ip-address: true #显示ip

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.athrw.springcloud.entities