server:
  port: 8002
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002 #修改服务名
    prefer-ip-address: true #显示ip
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.athrw.springcloud.entities